### ISSUE TITLE
Split driver interface into CallerDriver and RoleDriver?

### ISSUE THREAD

**Issue by driesvints** [BeatSwitch/lock#8]
I'm thinking about splitting these contracts so people can optionally implement the `RoleDriver` contract. This allows them to not specifically have to user the role functionality.

This could get messy if we also do #4 since we would have 4 interfaces that way.

Thoughts?

**Comment by sagikazarmark** [comment]
It is a hard question I think. For now, it is good. But for the future, this should be reviewed. I can imagine some sort of aggregate driver which finds the appropriate driver for an object making it very simple to work with multiple drivers at once. So I would say put it on the roadmap somewhere, because this part needs some rethinking, especially when groups will be introduced.
